export const weeklyResults = [
  'den,Covers Spread,Thu',
  'nor,Over,Thu',
  'jax,Covers Spread,Sun',
  'jax,Over,Sun',
  'sea,Covers Spread,Sun',
  'atl,Over,Sun',
  'buf,Covers Spread,Sun',
  'oti,Under,Sun',
  'cle,Covers Spread,Sun',
  'cle,Over,Sun',
  'gnb,Covers Spread,Sun',
  'gnb,Over,Sun',
  'mia,Covers Spread,Sun',
  'clt,Over,Sun',
  'det,Covers Spread,Sun',
  'min,Over,Sun',
  'nyg,Covers Spread,Sun',
  'nyg,Over,Sun',
  'ram,Covers Spread,Sun',
  'rai,Under,Sun',
  'was,Covers Spread,Sun',
  'was,Over,Sun',
  'sfo,Covers Spread,Sun',
  'sfo,Over,Sun',
  'pit,Covers Spread,Sun',
  'pit,Over,Sun',
  'rav,Covers Spread,Mon',
  'tam,Over,Mon',
  'sdg,Covers Spread,Mon',
  'crd,Over,Mon',
];
