export const upcomingWeekData = [
  'Raiders_Rams_Thu',
  'Jets_Bills_Sun',
  'Browns_Bengals_Sun',
  'Texans_Cowboys_Sun',
  'Vikings_Lions_Sun',
  'Jaguars_Titans_Sun',
  'Eagles_Giants_Sun',
  'Ravens_Steelers_Sun',
  'Dolphins_Chargers_Sun',
  'Buccaneers_49ers_Sun',
  'Panthers_Seahawks_Sun',
  'Chiefs_Broncos_Sun',
  'Patriots_Cardinals_Mon',
];
